version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bridge-network
    

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_MYSQL_USER: test
      WORDPRESS_MYSQL_PASSWORD: test

    volumes:
      - /var/www/html

    networks:
      - bridge-network
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 7080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bridge-network



  drupal:
    image: drupal:latest
    container_name: drupal
    restart: always
    ports:
      - 9080:80
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

    volumes:
      - /var/www/private
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    
    networks:
      - bridge-network
      
      


networks:
  bridge-network:
    driver: bridge

volumes:
  db_data:

